package com.example.benchmatch.matching;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Extends ParallelRunVerification's approach (standalone, no JUnit/Spring) to cover EVERY classified persona pairing,
 * not just Fullstack Java: Fullstack Java x Fullstack Java (re-checked here too), Fullstack .NET x Fullstack .NET
 * (verified for the first time), and Frontend x Frontend (verified for the first time, and the reason the
 * Frontend-Frontend branch was ported into MatchingService on 2026-09-28).
 * <p>
 * Ground truth was generated by export_full_ground_truth.py in bench-match-cli, which calls the REAL, unmodified
 * classify_inputs.py/ build_matches.py functions (from cli_pkg/bench-match-cli — the authoritative source; see
 * MatchingService's class Javadoc for the stale-duplicate-file mixup this session had and corrected) against the real
 * AFD-Supply.xlsx/Demand.xlsx data.
 * <p>
 * Run with: java -cp <compiled classes> com.hcltech.benchmatch.matching.FullPersonaVerification <csv-dir>
 */
public class FullPersonaVerification {

    public static void main(String[] args) throws IOException {
        String csvDir = args.length > 0 ? args[0] : ".";
        List<Map<String, String>> supplyRows = readCsv(Path.of(csvDir, "full_supply_classified.csv"));
        List<Map<String, String>> demandRows = readCsv(Path.of(csvDir, "full_demand_classified.csv"));
        List<Map<String, String>> groundTruth = readCsv(Path.of(csvDir, "full_match_rows_ground_truth.csv"));

        System.out.println("Loaded: " + supplyRows.size() + " supply rows, " + demandRows.size()
                + " demand rows, " + groundTruth.size() + " ground-truth pairing rows.");

        // ---------------------------------------------------------------
        // Part 1: classification port verification (all personas)
        // ---------------------------------------------------------------
        int supplyMismatch = 0;
        Map<String, ClassificationResult> empClassified = new LinkedHashMap<>();
        for (Map<String, String> row : supplyRows) {
            String empCode = normalizeCode(row.get("Employee Code"));
            ClassificationResult javaResult = SupplyClassifier.classify(row.get("Skill Cluster"));
            empClassified.put(empCode, javaResult);

            boolean mismatch = !Objects.equals(nz(javaResult.persona()), nz(row.get("persona")))
                    || !Objects.equals(nz(javaResult.completeness()), nz(row.get("completeness")))
                    || !Objects.equals(javaResult.namedAccessories(), parsePyList(row.get("named_accessories")))
                    || !Objects.equals(javaResult.frameworkConfirmed(), parsePyBool(row.get("framework_confirmed")));
            if (mismatch) {
                supplyMismatch++;
                if (supplyMismatch <= 8) {
                    System.out.println("SUPPLY MISMATCH emp=" + empCode + " raw='" + row.get("Skill Cluster")
                            + "' java=" + javaResult + " python(persona=" + row.get("persona")
                            + ", completeness=" + row.get("completeness")
                            + ", accessories=" + row.get("named_accessories")
                            + ", framework=" + row.get("framework_confirmed") + ")");
                }
            }
        }
        System.out.println("Supply classification: " + (supplyRows.size() - supplyMismatch) + "/"
                + supplyRows.size() + " match Python exactly.");

        int demandMismatch = 0;
        Map<String, ClassificationResult> demClassified = new LinkedHashMap<>();
        for (Map<String, String> row : demandRows) {
            String reqId = row.get("Job Requisition ID");
            ClassificationResult javaResult = DemandClassifier.classify(row.get("Final Skill Cluster"));
            demClassified.put(reqId, javaResult);

            boolean mismatch = !Objects.equals(nz(javaResult.persona()), nz(row.get("persona")))
                    || !Objects.equals(nz(javaResult.subPersona()), nz(row.get("sub_persona")))
                    || !Objects.equals(javaResult.namedAccessories(), parsePyList(row.get("named_accessories")))
                    || !Objects.equals(javaResult.frameworkConfirmed(), parsePyBool(row.get("framework_confirmed")));
            if (mismatch) {
                demandMismatch++;
                if (demandMismatch <= 8) {
                    System.out.println("DEMAND MISMATCH req=" + reqId + " raw='" + row.get("Final Skill Cluster")
                            + "' java=" + javaResult + " python(persona=" + row.get("persona")
                            + ", sub_persona=" + row.get("sub_persona")
                            + ", accessories=" + row.get("named_accessories")
                            + ", framework=" + row.get("framework_confirmed") + ")");
                }
            }
        }
        System.out.println("Demand classification: " + (demandRows.size() - demandMismatch) + "/"
                + demandRows.size() + " match Python exactly.");

        // ---------------------------------------------------------------
        // Part 2: matching-logic port verification, broken out by
        // (emp_persona, dem_persona) pair so a Frontend-only or .NET-only
        // regression doesn't hide inside an aggregate pass/fail.
        // ---------------------------------------------------------------
        Map<String, Map<String, String>> supplyByCode = new LinkedHashMap<>();
        for (Map<String, String> row : supplyRows) {
            supplyByCode.put(normalizeCode(row.get("Employee Code")), row);
        }
        Map<String, Map<String, String>> demandByReq = new LinkedHashMap<>();
        for (Map<String, String> row : demandRows) {
            demandByReq.put(row.get("Job Requisition ID"), row);
        }

        MatchingService svc = new MatchingService();
        Map<String, int[]> perPairStats = new TreeMap<>(); // pairKey -> [checked, tierMismatch, qualityMismatch]
        int totalMismatchPrinted = 0;

        for (Map<String, String> gt : groundTruth) {
            String empCode = normalizeCode(gt.get("employee_code"));
            String reqId = gt.get("job_req_id");
            Map<String, String> empRow = supplyByCode.get(empCode);
            Map<String, String> demRow = demandByReq.get(reqId);
            if (empRow == null || demRow == null) {
                continue;
            }

            ClassificationResult emp = empClassified.get(empCode);
            ClassificationResult dem = demClassified.get(reqId);
            String pairKey = gt.get("emp_persona") + " x " + gt.get("dem_persona");

            SignalResult sk = svc.skillSignal(emp, dem);
            if (sk.quality().equals("no_relation")) {
                perPairStats.computeIfAbsent(pairKey, k -> new int[3]);
                continue; // Java-side says unrelated where ground truth says otherwise — counted below
            }
            SignalResult bd = svc.bandSignal(empRow.get("Sub Band"), demRow.get("Demand Sub Band Name"));
            SignalResult lo = svc.locationSignal(empRow.get("Employee Location"),
                    demRow.get("Personnel Sub Area Name"), demRow.get("Pan India"));
            String tier = svc.overallTier(sk, bd, lo);

            int[] stats = perPairStats.computeIfAbsent(pairKey, k -> new int[3]);
            stats[0]++; // checked

            String pyTier = gt.get("overall_tier");
            String pySkillQ = gt.get("skill_quality");
            String pyBandQ = gt.get("band_quality");
            String pyLocQ = gt.get("loc_quality");

            boolean tierMismatch = !tier.equals(pyTier);
            boolean qualityMismatch = !sk.quality().equals(pySkillQ) || !bd.quality().equals(pyBandQ) || !lo.quality().equals(pyLocQ);
            if (tierMismatch) stats[1]++;
            if (qualityMismatch) stats[2]++;

            if ((tierMismatch || qualityMismatch) && totalMismatchPrinted < 15) {
                totalMismatchPrinted++;
                System.out.println("MATCH MISMATCH [" + pairKey + "] emp=" + empCode + " req=" + reqId
                        + " java(tier=" + tier + ", skill=" + sk.quality() + ", band=" + bd.quality()
                        + ", loc=" + lo.quality() + ")"
                        + " python(tier=" + pyTier + ", skill=" + pySkillQ + ", band=" + pyBandQ
                        + ", loc=" + pyLocQ + ")");
            }
        }

        // Count ground-truth rows the Java side wrongly called no_relation
        // (those never entered perPairStats' "checked" count above).
        Map<String, Integer> groundTruthCountByPair = new TreeMap<>();
        for (Map<String, String> gt : groundTruth) {
            String pairKey = gt.get("emp_persona") + " x " + gt.get("dem_persona");
            groundTruthCountByPair.merge(pairKey, 1, Integer::sum);
        }

        System.out.println();
        System.out.println("Per (employee-persona x demand-persona) pair results:");
        boolean allGood = supplyMismatch == 0 && demandMismatch == 0;
        for (var e : groundTruthCountByPair.entrySet()) {
            int[] stats = perPairStats.getOrDefault(e.getKey(), new int[3]);
            int checked = stats[0];
            int missedAsNoRelation = e.getValue() - checked;
            boolean pairGood = missedAsNoRelation == 0 && stats[1] == 0 && stats[2] == 0;
            allGood = allGood && pairGood;
            System.out.println("  " + e.getKey() + ": " + checked + "/" + e.getValue() + " checked, "
                    + "wrongly-no_relation=" + missedAsNoRelation + ", tier mismatches=" + stats[1]
                    + ", quality mismatches=" + stats[2] + " -> " + (pairGood ? "PASS" : "FAIL"));
        }

        System.out.println();
        System.out.println(allGood ? "RESULT: PASS — Java port matches Python exactly across all classified persona pairs."
                : "RESULT: FAIL — see mismatches above.");
        if (!allGood) {
            System.exit(1);
        }
    }

    private static String normalizeCode(String s) {
        if (s == null) return null;
        return s.endsWith(".0") ? s.substring(0, s.length() - 2) : s;
    }

    private static String nz(String s) {
        return (s == null || s.isBlank() || s.equalsIgnoreCase("nan")) ? null : s;
    }

    private static Boolean parsePyBool(String s) {
        if (s == null || s.isBlank() || s.equalsIgnoreCase("nan")) return null;
        return Boolean.parseBoolean(s.trim());
    }

    private static List<String> parsePyList(String s) {
        if (s == null || s.isBlank()) return List.of();
        String t = s.trim();
        if (t.equals("[]")) return List.of();
        if (t.startsWith("[") && t.endsWith("]")) {
            t = t.substring(1, t.length() - 1);
        }
        List<String> out = new ArrayList<>();
        for (String part : t.split(",")) {
            String v = part.trim();
            if (v.startsWith("'") && v.endsWith("'") && v.length() >= 2) {
                v = v.substring(1, v.length() - 1);
            } else if (v.startsWith("\"") && v.endsWith("\"") && v.length() >= 2) {
                v = v.substring(1, v.length() - 1);
            }
            if (!v.isEmpty()) {
                out.add(v);
            }
        }
        return out;
    }

    private static List<Map<String, String>> readCsv(Path path) throws IOException {
        List<String> lines = Files.readAllLines(path);
        List<List<String>> records = new ArrayList<>();
        StringBuilder field = new StringBuilder();
        List<String> record = new ArrayList<>();
        boolean inQuotes = false;
        for (String line : lines) {
            int i = 0;
            while (i < line.length()) {
                char c = line.charAt(i);
                if (inQuotes) {
                    if (c == '"') {
                        if (i + 1 < line.length() && line.charAt(i + 1) == '"') {
                            field.append('"');
                            i++;
                        } else {
                            inQuotes = false;
                        }
                    } else {
                        field.append(c);
                    }
                } else {
                    if (c == '"') {
                        inQuotes = true;
                    } else if (c == ',') {
                        record.add(field.toString());
                        field.setLength(0);
                    } else {
                        field.append(c);
                    }
                }
                i++;
            }
            if (inQuotes) {
                field.append('\n');
            } else {
                record.add(field.toString());
                field.setLength(0);
                records.add(record);
                record = new ArrayList<>();
            }
        }

        List<String> header = records.get(0);
        List<Map<String, String>> out = new ArrayList<>();
        for (int r = 1; r < records.size(); r++) {
            List<String> rec = records.get(r);
            Map<String, String> row = new LinkedHashMap<>();
            for (int c = 0; c < header.size() && c < rec.size(); c++) {
                row.put(header.get(c), rec.get(c));
            }
            out.add(row);
        }
        return out;
    }
}
