package com.example.benchmatch.matching;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Standalone (no JUnit/Spring) parallel-run comparison harness — the deliverable called for in
 * demand-supply-mapping-requirements.md's "Web App — Architecture & Technology" section: run the same real input
 * through both the Python pipeline and the Java port, diff row-for-row.
 * <p>
 * This first run covers the Fullstack Java persona only, per the "one persona, end-to-end, verified" plan. Ground truth
 * CSVs were generated by export_fullstack_java_ground_truth.py in bench-match-cli, which calls the REAL, unmodified
 * classify_inputs.py/build_matches.py functions against the real AFD-Supply.xlsx/Demand.xlsx data — this class never
 * re-derives what Python "should" produce, only compares against what it actually did produce.
 * <p>
 * Run with: java -cp <compiled classes> com.hcltech.benchmatch.matching.ParallelRunVerification <csv-dir>
 */
public class ParallelRunVerification {

    public static void main(String[] args) throws IOException {
        String csvDir = args.length > 0 ? args[0] : ".";
        List<Map<String, String>> supplyRows = readCsv(Path.of(csvDir, "fj_supply_classified.csv"));
        List<Map<String, String>> demandRows = readCsv(Path.of(csvDir, "fj_demand_classified.csv"));
        List<Map<String, String>> groundTruth = readCsv(Path.of(csvDir, "fj_match_rows_ground_truth.csv"));

        System.out.println("Loaded: " + supplyRows.size() + " supply rows, " + demandRows.size()
                + " demand rows, " + groundTruth.size() + " ground-truth pairing rows.");

        // ---------------------------------------------------------------
        // Part 1: classification port verification
        // ---------------------------------------------------------------
        int supplyMismatch = 0;
        Map<String, ClassificationResult> empClassified = new LinkedHashMap<>();
        for (Map<String, String> row : supplyRows) {
            String empCode = normalizeCode(row.get("Employee Code"));
            String rawSkillCluster = row.get("Skill Cluster");
            ClassificationResult javaResult = SupplyClassifier.classify(rawSkillCluster);
            empClassified.put(empCode, javaResult);

            String pyPersona = nz(row.get("persona"));
            String pyCompleteness = nz(row.get("completeness"));
            List<String> pyAccessories = parsePyList(row.get("named_accessories"));
            Boolean pyFramework = parsePyBool(row.get("framework_confirmed"));

            boolean mismatch = !Objects.equals(nz(javaResult.persona()), pyPersona)
                    || !Objects.equals(nz(javaResult.completeness()), pyCompleteness)
                    || !Objects.equals(javaResult.namedAccessories(), pyAccessories)
                    || !Objects.equals(javaResult.frameworkConfirmed(), pyFramework);
            if (mismatch) {
                supplyMismatch++;
                if (supplyMismatch <= 5) {
                    System.out.println("SUPPLY CLASSIFICATION MISMATCH emp=" + empCode
                            + " raw='" + rawSkillCluster + "'"
                            + " java=" + javaResult
                            + " python(persona=" + pyPersona + ", completeness=" + pyCompleteness
                            + ", accessories=" + pyAccessories + ", framework=" + pyFramework + ")");
                }
            }
        }
        System.out.println("Supply classification: " + (supplyRows.size() - supplyMismatch) + "/"
                + supplyRows.size() + " match Python exactly.");

        int demandMismatch = 0;
        Map<String, ClassificationResult> demClassified = new LinkedHashMap<>();
        for (Map<String, String> row : demandRows) {
            String reqId = row.get("Job Requisition ID");
            String rawSkillText = row.get("Final Skill Cluster");
            ClassificationResult javaResult = DemandClassifier.classify(rawSkillText);
            demClassified.put(reqId, javaResult);

            String pyPersona = nz(row.get("persona"));
            List<String> pyAccessories = parsePyList(row.get("named_accessories"));
            Boolean pyFramework = parsePyBool(row.get("framework_confirmed"));

            boolean mismatch = !Objects.equals(nz(javaResult.persona()), pyPersona)
                    || !Objects.equals(javaResult.namedAccessories(), pyAccessories)
                    || !Objects.equals(javaResult.frameworkConfirmed(), pyFramework);
            if (mismatch) {
                demandMismatch++;
                if (demandMismatch <= 5) {
                    System.out.println("DEMAND CLASSIFICATION MISMATCH req=" + reqId
                            + " raw='" + rawSkillText + "'"
                            + " java=" + javaResult
                            + " python(persona=" + pyPersona + ", accessories=" + pyAccessories
                            + ", framework=" + pyFramework + ")");
                }
            }
        }
        System.out.println("Demand classification: " + (demandRows.size() - demandMismatch) + "/"
                + demandRows.size() + " match Python exactly.");

        // ---------------------------------------------------------------
        // Part 2: matching-logic port verification (band/location/skill/tier)
        // ---------------------------------------------------------------
        Map<String, Map<String, String>> supplyByCode = new LinkedHashMap<>();
        for (Map<String, String> row : supplyRows) {
            supplyByCode.put(normalizeCode(row.get("Employee Code")), row);
        }
        Map<String, Map<String, String>> demandByReq = new LinkedHashMap<>();
        for (Map<String, String> row : demandRows) {
            demandByReq.put(row.get("Job Requisition ID"), row);
        }

        MatchingService svc = new MatchingService();
        int tierMismatch = 0;
        int qualityMismatch = 0;
        int checked = 0;
        Map<String, Integer> javaTierCounts = new TreeMap<>();

        for (Map<String, String> gt : groundTruth) {
            String empCode = normalizeCode(gt.get("employee_code"));
            String reqId = gt.get("job_req_id");
            Map<String, String> empRow = supplyByCode.get(empCode);
            Map<String, String> demRow = demandByReq.get(reqId);
            if (empRow == null || demRow == null) {
                continue; // shouldn't happen — ground truth was built from these same two files
            }

            ClassificationResult emp = empClassified.get(empCode);
            ClassificationResult dem = demClassified.get(reqId);

            SignalResult sk = svc.skillSignal(emp, dem);
            if (sk.quality().equals("no_relation")) {
                continue; // matches Python's own "continue" on no_relation — no row generated
            }
            SignalResult bd = svc.bandSignal(empRow.get("Sub Band"), demRow.get("Demand Sub Band Name"));
            SignalResult lo = svc.locationSignal(empRow.get("Employee Location"),
                    demRow.get("Personnel Sub Area Name"), demRow.get("Pan India"));
            String tier = svc.overallTier(sk, bd, lo);

            checked++;
            javaTierCounts.merge(tier, 1, Integer::sum);

            String pyTier = gt.get("overall_tier");
            String pySkillQ = gt.get("skill_quality");
            String pyBandQ = gt.get("band_quality");
            String pyLocQ = gt.get("loc_quality");

            if (!tier.equals(pyTier)) {
                tierMismatch++;
            }
            if (!sk.quality().equals(pySkillQ) || !bd.quality().equals(pyBandQ) || !lo.quality().equals(pyLocQ)) {
                qualityMismatch++;
            }
            if ((!tier.equals(pyTier) || !sk.quality().equals(pySkillQ)) && (tierMismatch + qualityMismatch) <= 10) {
                System.out.println("MATCH MISMATCH emp=" + empCode + " req=" + reqId
                        + " java(tier=" + tier + ", skill=" + sk.quality() + ", band=" + bd.quality()
                        + ", loc=" + lo.quality() + ")"
                        + " python(tier=" + pyTier + ", skill=" + pySkillQ + ", band=" + pyBandQ
                        + ", loc=" + pyLocQ + ")");
            }
        }

        System.out.println();
        System.out.println("Pairing rows checked (skill quality != no_relation on Java side): " + checked
                + " / " + groundTruth.size() + " ground-truth rows");
        System.out.println("Tier mismatches: " + tierMismatch);
        System.out.println("Signal quality mismatches (skill/band/loc): " + qualityMismatch);
        System.out.println("Java-computed tier distribution: " + javaTierCounts);

        boolean allGood = supplyMismatch == 0 && demandMismatch == 0 && tierMismatch == 0
                && qualityMismatch == 0 && checked == groundTruth.size();
        System.out.println();
        System.out.println(allGood ? "RESULT: PASS — Java port matches Python exactly on Fullstack Java."
                : "RESULT: FAIL — see mismatches above.");
        if (!allGood) {
            System.exit(1);
        }
    }

    private static String normalizeCode(String s) {
        if (s == null) return null;
        // pandas wrote Employee Code as a float ("40208431.0") in both CSVs
        // consistently — strip the trailing ".0" so the two files join.
        return s.endsWith(".0") ? s.substring(0, s.length() - 2) : s;
    }

    private static String nz(String s) {
        return (s == null || s.isBlank() || s.equalsIgnoreCase("nan")) ? null : s;
    }

    private static Boolean parsePyBool(String s) {
        if (s == null || s.isBlank() || s.equalsIgnoreCase("nan")) return null;
        return Boolean.parseBoolean(s.trim());
    }

    /**
     * Parses pandas' default str(list) rendering, e.g. "['DevOps', 'React']" or "[]".
     */
    private static List<String> parsePyList(String s) {
        if (s == null || s.isBlank()) return List.of();
        String t = s.trim();
        if (t.equals("[]")) return List.of();
        if (t.startsWith("[") && t.endsWith("]")) {
            t = t.substring(1, t.length() - 1);
        }
        List<String> out = new ArrayList<>();
        for (String part : t.split(",")) {
            String v = part.trim();
            if (v.startsWith("'") && v.endsWith("'") && v.length() >= 2) {
                v = v.substring(1, v.length() - 1);
            } else if (v.startsWith("\"") && v.endsWith("\"") && v.length() >= 2) {
                v = v.substring(1, v.length() - 1);
            }
            if (!v.isEmpty()) {
                out.add(v);
            }
        }
        return out;
    }

    /**
     * Minimal RFC4180-ish CSV reader — handles quoted fields with embedded commas/quotes, which pandas' to_csv produces
     * for the raw skill-text columns (they contain literal commas). No external dependency.
     */
    private static List<Map<String, String>> readCsv(Path path) throws IOException {
        List<String> lines = Files.readAllLines(path);
        List<List<String>> records = new ArrayList<>();
        StringBuilder field = new StringBuilder();
        List<String> record = new ArrayList<>();
        boolean inQuotes = false;
        for (int li = 0; li < lines.size(); li++) {
            String line = lines.get(li);
            int i = 0;
            while (i < line.length()) {
                char c = line.charAt(i);
                if (inQuotes) {
                    if (c == '"') {
                        if (i + 1 < line.length() && line.charAt(i + 1) == '"') {
                            field.append('"');
                            i++;
                        } else {
                            inQuotes = false;
                        }
                    } else {
                        field.append(c);
                    }
                } else {
                    if (c == '"') {
                        inQuotes = true;
                    } else if (c == ',') {
                        record.add(field.toString());
                        field.setLength(0);
                    } else {
                        field.append(c);
                    }
                }
                i++;
            }
            if (inQuotes) {
                // embedded newline inside a quoted field — continue accumulating
                field.append('\n');
            } else {
                record.add(field.toString());
                field.setLength(0);
                records.add(record);
                record = new ArrayList<>();
            }
        }

        List<String> header = records.get(0);
        List<Map<String, String>> out = new ArrayList<>();
        for (int r = 1; r < records.size(); r++) {
            List<String> rec = records.get(r);
            Map<String, String> row = new LinkedHashMap<>();
            for (int c = 0; c < header.size() && c < rec.size(); c++) {
                row.put(header.get(c), rec.get(c));
            }
            out.add(row);
        }
        return out;
    }
}
